engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
    - frontend/scripts/app/**
exclude_paths:
  - node_modules/*
  - eslint-rules/*
  - frontend/scripts/libs/*
