engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
    - frontend/scripts/app/**
    # Add paths for backend code checks
exclude_paths:
  - node_modules/*
  - eslint-rules/*
  - frontend/scripts/libs/*
