engines:
  eslint:
    enabled: true
    checks:
      async-await/space-after-async:
        enabled: false
      async-await/space-after-await:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
    - frontend/scripts/app/**
    - api/**
    - config/**
    - test/**
exclude_paths:
  - node_modules/*
  - eslint-rules/*
  - frontend/scripts/libs/*
