engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
    - frontend/scripts/app/**
    - api/**
    - config/**
    - test/**
exclude_paths:
  - tests/**/*
  - "**/node_modules/**/*"
  - "**/eslint-rules/**/*"
  - "**/frontend/scripts/libs/**/*"
